# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12
        AppBundle\Entity\Users:
            algorithm: bcrypt
            cost: 12
            
    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        chain_provider:
            chain:
                providers: [in_memory, users_provider]
        in_memory:
            memory:
                users:
                    superadmin:
                        password: $2y$12$o9QNMO05m0HRdW0RvFdLoeBB60hFvfKpKcWWrMkYMLebBz.0/Lrgu
                        roles: 'ROLE_SUPERADMIN'
        users_provider:
            entity:
                class: AppBundle:Users
                property: username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login_firewall:
            pattern:   ^/login$
            anonymous: ~
            
        wsse_secured:
          pattern:   ^/api/
          stateless: true
          wsse: true
        
        general_area:
            pattern:  ^
            anonymous:  ~
            provider: chain_provider
            http_basic: ~
            form_login:
                check_path: /login_check
                login_path: /login
                default_target_path: /
                always_use_default_target_path: true
                use_forward: false
            access_denied_url: /denied
            logout:
                path:   /logout
                target: /login
                
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/rest, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: [ROLE_SUPERADMIN, ROLE_ADMIN, ROLE_USER] }
        
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
