device_index:
    path:     /
    defaults: { _controller: "AppBundle:Device:index" }
    methods:  GET
    options:
        expose: true

device_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Device:show" }
    methods:  GET
    options:
        expose: true

device_new:
    path:     /new
    defaults: { _controller: "AppBundle:Device:new" }
    methods:  [GET, POST]
    options:
        expose: true

device_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Device:edit" }
    methods:  [GET, POST]
    options:
        expose: true

device_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Device:delete" }
    methods:  DELETE
    options:
        expose: true

device_find_all:
    path:     /findAll
    defaults: { _controller: "AppBundle:Device:findAll" }
    methods:  GET
    options:
        expose: true
