polygon_index:
    path:     /
    defaults: { _controller: "AppBundle:Polygon:index" }
    methods:  GET
    options:
        expose: true

polygon_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Polygon:show" }
    methods:  GET
    options:
        expose: true

polygon_new:
    path:     /new
    defaults: { _controller: "AppBundle:Polygon:new" }
    methods:  [GET, POST]
    options:
        expose: true

polygon_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Polygon:edit" }
    methods:  [GET, POST]
    options:
        expose: true

polygon_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Polygon:delete" }
    methods:  DELETE
    options:
        expose: true

polygon_find_all:
    path:     /findAll
    defaults: { _controller: "AppBundle:Polygon:findAll" }
    methods:  GET
    options:
        expose: true
