role_index:
    path:     /
    defaults: { _controller: "AppBundle:Role:index" }
    methods:  GET
    options:
        expose: true

role_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Role:show" }
    methods:  GET
    options:
        expose: true

role_new:
    path:     /new
    defaults: { _controller: "AppBundle:Role:new" }
    methods:  [GET, POST]
    options:
        expose: true

role_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Role:edit" }
    methods:  [GET, POST]
    options:
        expose: true

role_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Role:delete" }
    methods:  DELETE
    options:
        expose: true

role_find_all:
    path:     /findAll
    defaults: { _controller: "AppBundle:Role:findAll" }
    methods:  GET
    options:
        expose: true
