users_index:
    path:     /
    defaults: { _controller: "AppBundle:Users:index" }
    methods:  GET
    options:
        expose: true

users_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Users:show" }
    methods:  GET
    options:
        expose: true

users_new:
    path:     /new
    defaults: { _controller: "AppBundle:Users:new" }
    methods:  [GET, POST]
    options:
        expose: true

users_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Users:edit" }
    methods:  [GET, POST]
    options:
        expose: true

users_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Users:delete" }
    methods:  DELETE
    options:
        expose: true
        
users_find_all:
    path:     /findAll
    defaults: { _controller: "AppBundle:Users:findAll" }
    methods:  GET
    options:
        expose: true
              
        
        
        