app_homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }
    
app_login:
     resource: "@AppBundle/Resources/config/routing/login.yml"
     prefix:   /
     
app_position:
    resource: "@AppBundle/Resources/config/routing/position.yml"
    prefix:   /position

app_polygon:
    resource: "@AppBundle/Resources/config/routing/polygon.yml"
    prefix:   /polygon

app_device:
    resource: "@AppBundle/Resources/config/routing/device.yml"
    prefix:   /device
    
app_role:
    resource: "@AppBundle/Resources/config/routing/role.yml"
    prefix:   /role
 
app_users:
    resource: "@AppBundle/Resources/config/routing/users.yml"
    prefix:   /users
    
app_alert:
    resource: "@AppBundle/Resources/config/routing/alert.yml"
    prefix:   /alert

rest : 
    resource : "@AppBundle/Resources/config/routing/rest.yml"
    prefix : /rest